server {
    listen 80;
    resolver 127.0.0.11 valid=1s ipv6=off;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /proxy/access/ {
        set $upstream access-lb:8080;
        rewrite ^/proxy/access/(.*)$ /api/access/$1 break;
        proxy_pass http://$upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
